Repository unb-mds/Gastos-DF-2024-02, pull requests merged in 2024-12, with the labels that each got.

#81 docs: atualização da README.md
  README.md
Labels: documentação

#89 feat: Organização da tables com json e js
  codigo/app.py
  codigo/templates/tables.html
Labels: enhancement

#101 docs: atualiza README com e-mail de contato e remove referência à pasta 'docs'
  README.md
Labels: documentação

#102 fix: Apagando duplicata
  documentacao/CONTRIBUTING.md
Labels: fix

#100 docs/99
  documentacao/sprints/sprint4.md
Labels: documentação

#103 Criando o arquivo PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentação

#108 Doc/atas
  documentacao/atas/ata_10_12_24.md
  documentacao/atas/atas_reunioes_semanais/ata_09_12_24.md
Labels: documentação

#111 docs/110
  documentacao/scrum/scrum_pt2.md
Labels: documentação

#112 fix(pages): correção do git pages
  mkdocs/docs/arquitetura/arquitetura.md
  mkdocs/docs/matriz_de_competencias/resultados.md
Labels: fix

#113 fix/documentacao da arquitetura e da matriz de competências
  documentacao/arquitetura/arquitetura.md
  documentacao/matriz_de_competencias/resultados.md
Labels: documentação, fix

#120 docs/atualizacao-arquivos-mkdocs
  mkdocs/docs/index.md
  mkdocs/docs/scrum/scrum_pt2.md
  mkdocs/docs/sprints/organizacao.md
Labels: documentação

#125 Docs/116
  docs/sprints/sprint6.md
Labels: documentação

#124 docs: atualizar arquitetura para monolítica
  docs/arquitetura/arquitetura.md
  docs/assets/DiagramaArquitetura.jpeg
  docs/assets/DiagramaArquitetura.png
  docs/scrum/scrum.md
  docs/sprints/sprint0.md
  docs/sprints/sprint1.md
Labels: documentação

#128 Update organizacao.md
  docs/sprints/organizacao.md
Labels: documentação

#131 docs/130
  docs/sprints/sprint7.md
Labels: documentação

#129 docs: Inclusão do uso de duas APIs na coleta de dados
  docs/arquitetura/arquitetura.md
  docs/assets/DiagramaArquitetura.jpeg
Labels: documentação

#136 docs/135
  docs/atas/ata_27_12_24.md
Labels: documentação
