Repository unb-mds/Gastos-DF-2024-02, pull requests merged in 2025-01, with the labels that each got.

#138 docs/137
  docs/prototipo-alta-fidelidade/v0.1.0/design-do-site-v0.1.0.pdf
  docs/prototipo-alta-fidelidade/v0.1.0/landing-page.pdf
  docs/prototipo-alta-fidelidade/v0.1.0/v0.1.0.md
  docs/prototipo-alta-fidelidade/v0.2.0/design-do-site-v0.2.0.pdf
  docs/prototipo-alta-fidelidade/v0.2.0/v0.2.0.md
Labels: documentação

#141 docs: criacao das atas de reuniao da sprint 9
  docs/atas/ata_07_01_25.md
  docs/atas/ata_09_01_25.md
  docs/atas/atas_reunioes_semanais/ata_06_01_25.md
Labels: documentação

#139 Script do Bolsa Família
  .github/workflows/coleta_de_dados.yml
  actions/bolsafamilia.py
  actions/json/bolsafamilia.json
Labels: feature

#143 Atualização organizacao.md
  docs/sprints/organizacao.md
Labels: documentação

#144 Adição da documentação sobre XP
  docs/xp/xp.md
Labels: documentação

#147 docs: adicionamos a documentacao da sprint 8
  docs/sprints/sprint8.md
Labels: documentação

#152 docs/151
  docs/collection-api-portal-transparencia/v0.1.0/API de Dados Portal da Transparência.postman_collection-v0.1.0.json
  docs/collection-api-portal-transparencia/v0.2.0/API de Dados Portal da Transparência.postman_collection-v0.2.0.json
  docs/collection-api-portal-transparencia/v0.2.0/API de Dados Querido Diário.postman_collection-v0.2.0.json
  mkdocs.yml
Labels: documentação

#159 Atualização organizacao.md
  docs/sprints/organizacao.md
Labels: documentação

#160 Adicionando arquivo sprint9.md
  docs/sprints/sprint9.md
Labels: documentação

#168 Refatoração com foco na modularização e organização do código.
  codigo/app.py
  codigo/static/scripts/charts.js
  codigo/static/scripts/tables.js
  codigo/templates/base.html
  codigo/templates/graficos.html
  codigo/templates/tabelas.html
  codigo/templates/tables.html
  codigo/utils/__pycache__/carregador_dados.cpython-312.pyc
  codigo/utils/__pycache__/carregar_dados.cpython-312.pyc
  codigo/utils/__pycache__/conversores.cpython-312.pyc
  codigo/utils/__pycache__/processador_dados.cpython-312.pyc
  codigo/utils/carregador_dados.py
  codigo/utils/conversores.py
  codigo/utils/processador_dados.py
Labels: feature, fix

#171 docs: Arrumando documentação da organizacao.md
  docs/sprints/organizacao.md
Labels: documentação

#167 Develop
  .gitignore
  actions/json/despesas_20000_Presidência_da_República.json
  actions/json/despesas_22000_Ministério_da_Agricultura_e_Pecuária.json
  actions/json/despesas_30000_Ministério_da_Justiça_e_Segurança_Pública.json
  actions/json/despesas_35000_Ministério_das_Relações_Exteriores.json
  actions/json/despesas_36000_Ministério_da_Saúde.json
  actions/json/despesas_40000_Ministério_do_Trabalho_e_Emprego.json
  actions/json/despesas_51000_Ministério_do_Esporte.json
  actions/json/despesas_52000_Ministério_da_Defesa.json
  actions/json/despesas_53000_Ministério_da_Integração_e_do_Desenvolvimento_Regional.json
  codigo/app.py
  codigo/static/css/style.css
  codigo/static/images/logo.png
  codigo/static/scripts/charts.js
  codigo/static/scripts/tables.js
  codigo/templates/base.html
  codigo/templates/charts.html
  codigo/templates/graficos.html
  codigo/templates/tabelas.html
  codigo/templates/tables.html
  codigo/utils/__pycache__/carregador_dados.cpython-312.pyc
  codigo/utils/__pycache__/carregar_dados.cpython-312.pyc
  codigo/utils/__pycache__/conversores.cpython-312.pyc
  codigo/utils/__pycache__/processador_dados.cpython-312.pyc
  codigo/utils/carregador_dados.py
  codigo/utils/conversores.py
  codigo/utils/processador_dados.py
  requirements.txt
Labels: feature

#169 Feat/166
  codigo/app.py
  codigo/static/images/Exemplo1.png
  codigo/static/images/Interacao1.png
  codigo/static/images/tabela1.JPG
  codigo/static/images/tabela2.JPG
  codigo/static/images/tabela3.JPG
  codigo/templates/about.html
  codigo/templates/base.html
Labels: feature

#172 doc/fix
  .github/workflows/coleta_de_dados.yml
  README.md
  docs/index.md
  mkdocs.yml
Labels: documentação

#170 feat: Adição de valores médios nos gráficos
  Procfile
  codigo/static/css/style.css
  codigo/static/scripts/charts.js
Labels: feature

#174 Docs/organizacao
  docs/sprints/organizacao.md
Labels: documentação

#173 refactor/164
  .pre-commit-config.yaml
  actions/bolsafamilia.py
  actions/compras.py
  actions/despesas_por_orgao.py
  codigo/app.py
  codigo/static/css/style.css
  codigo/static/scripts/graficos.js
  codigo/static/scripts/tabelas.js
  codigo/static/scripts/tables.js
  codigo/templates/base.html
  codigo/templates/graficos.html
  codigo/templates/tabelas.html
  codigo/utils/carregador_dados.py
  codigo/utils/conversores.py
  codigo/utils/processador_dados.py
  requirements.txt
Labels: feature

#182 docs: Adiciona ata de reunião do dia 27/01
  docs/atas/atas_reunioes_semanais/ata_27_01_25.md
Labels: documentação
